const express = require('express')
const router = express.Router()
const login = require('../controller/admin')
const logout = require('../controller/admin')
const list = require('../controller/admin')
const editreferral = require('../controller/admin')
const referrals = require('../controller/admin')
const commission = require('../controller/admin')
const notify = require('../controller/admin')
const notifyall = require('../controller/admin')
const home = require('../controller/admin')
const auth=require('../middleware/auth')


router.post('/login', login)
router.get('/logout',auth, logout)
router.post('/list',auth, list)
router.post('/referrals',auth, referrals)
router.post('/editreferral',auth, editreferral)
router.post('/commission',auth, commission)
router.post('/notify',auth, notify)
router.get('/home',auth, home)
router.post('/notifyall',auth, notifyall)

module.exports = router