const express = require('express')
const router = express.Router()
const logout = require('../controller/partner')
const login = require('../controller/partner')
const upload = require('../controller/partner')
const referral = require('../controller/partner')
const commission = require('../controller/partner')
const notify = require('../controller/partner')
const user = require('../controller/partner')
const payout = require('../controller/partner')
const icon = require('../controller/partner')
const register = require('../controller/partner')
const mail = require('../controller/partner')
const auth=require('../middleware/auth')


router.post('/register', register)
router.post('/login', login)
router.get('/logout',auth, logout)
router.post('/upload',auth, upload)
router.post('/referral',auth, referral)
router.post('/commission',auth, commission)
router.get('/notify',auth, notify)
router.post('/icon',auth, icon)
router.get('/icon/:refid,auth', icon)
router.post('/payout',auth, payout)
router.post('/user',auth, user)
router.patch('/user',auth, user)
router.post('/mail',auth, mail)

module.exports = router
